In [15]:
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct")
model = AutoModelForCausalLM.from_pretrained("meta-llama/Meta-Llama-3.1-8B-Instruct")

sentence = "Question: How long is Camptown Racetrack ?\ntype: number\n\nQuestion: What is the name of the brilliant British economist behind its creation ?\ntype: human\n\nQuestion: Where do I find information for foreclosure properties on the Internet ?\ntype: location\n\nQuestion: Where did Ty Cobb grow up ?\ntype: location\n\nQuestion: How many teaspoons make up a tablespoon ?\ntype: number\n\nQuestion: What baseball expression came from the nautical term for ships sailing between the Atlantic and Pacific before the Panama Canal ?\ntype: description\n\nQuestion: What animal has been called The Poor Man's Cow ?\ntype: entity\n\nQuestion: What book opens : `` At a certain village in La Mancha, which I shall not name...'' ?\ntype: entity\n\nQuestion: What is the origin of the word, magic ?\ntype: description\n\nQuestion: Name the blind sculptress in love with the Fantastic Four's Thing.\ntype: human\n\nQuestion: Where can I find info on Alexander Mackenzie ?\ntype: location\n\nQuestion: How many years ago did Led Zeppelin release its last album ?\ntype: number\n\nQuestion: What does God create in the first sentence of the Bible ?\ntype: entity\n\nQuestion: What is the price for tuberculosis drugs ?\ntype: number\n\nQuestion: What were Baffin, Frobisher and Franklin looking for ?\ntype: entity\n\nQuestion: What do the red-and-white stripes on a barbershop pole stand for ?\ntype: description\n\nQuestion: How do doctors diagnose bone cancer ?\ntype: description\n\nQuestion: Where can I find a world atlas map online at no charge ?\ntype: location\n\nQuestion: In which Tennessee Williams play is one of the characters killed and devoured by a mob of starving children ?\ntype: entity\n\nQuestion: In what year did they build the Berlin Wall ?\ntype: number\n\nQuestion: What are the Nordic nations ?\ntype: location\n\nQuestion: Name the vessel used by the Atari Force in the DC comics.\ntype: entity\n\nQuestion: What are values ?\ntype: description\n\nQuestion: Where is McCarren Airport ?\ntype: location\n\nQuestion: Which of the following people is not associated with Andy Warhol ?\ntype: human\n\nQuestion: What information can you get me on Fairground Park in St. Louis\ntype: description\n\nQuestion: What according to the Kinsey Institute, is the sexual preference of four percent of American males ?\ntype: description\n\nQuestion: What is the origin of the term `` buffalo wings'' that is used as a menu item in bars across the nation for chicken wings in a spicey sauce ?\ntype: description\n\nQuestion: Who was the original Humpty Dumpty ?\ntype: human\n\nQuestion: How many equal sides are there on a scalene triangle ?\ntype: number\n\nQuestion: Where is Windsor Castle ?\ntype: location\n\nQuestion: Who directed The Wild Bunch ?\ntype: human\n\nQuestion: What is the chromosome number of an elephant ?\ntype: number\n\nQuestion: Where is Qatar ?\ntype: location\n\nQuestion: Who invented the Wonderbra ?\ntype: human\n\nQuestion: What is an example of an actual case of using the Fourteenth Amendment ?\ntype: description\n\nQuestion: What kind of creatures are the Canary Islands named for ?\ntype: entity\n\nQuestion: How can I register my website in Yahoo for free ?\ntype: description\n\nQuestion: What is the seafaring name for the southern tip of South America ?\ntype: location\n\nQuestion: Where can I find a case on Americans with Disabilities Act of 199 ?\ntype: location\n\nQuestion: What are those little blue reflectors in the middle of the road for ?\ntype: description\n\nQuestion: What California bridge was Don Brown the first to cross, on May 27, 1937 ?\ntype: location\n\nQuestion: What card game derived its name from biritch, or Russian Whist ?\ntype: entity\n\nQuestion: What company's logo is a `` W'' in a circle ?\ntype: human\n\nQuestion: What is a portal ?\ntype: description\n\nQuestion: What disease did August von Wassermann develop a specific test for in 196 ?\ntype: entity\n\nQuestion: What's the abbreviation for trinitrotoluene ?\ntype: abbreviation\n\nQuestion: Where did Bill Gates go to college ?\ntype: location\n\nQuestion: On what T.V. show could Tom Terrific be found ?\ntype: entity\n\nQuestion: Why do some clothing labels say `` Use a nonchlorine bleach'' ?\ntype: description\n\nQuestion: What is IOC an abbreviation of ?\ntype: abbreviation\n\nQuestion: What Nazi leader killed himself in jail just before he was to be executed as a war criminal ?\ntype: human\n\nQuestion: Who is the head of the World Bank ?\ntype: human\n\nQuestion: Who is the Prophet of Medina ?\ntype: human\n\nQuestion: Who discovered imaginary numbers ?\ntype: human\n\nQuestion: Which of the following famous people does not paint as a hobby ?\ntype: human\n\nQuestion: What is a caul ?\ntype: description\n\nQuestion: What does saliva consist of ?\ntype: entity\n\nQuestion: What capital is built around Monument Circle which contains soldiers and sailors monument ?\ntype: location\n\nQuestion: What are some tips for building a fire in a fireplace ?\ntype: entity\n\nQuestion: What deck of cards includes the Wheel of Fortune, the Lovers, and Death ?\ntype: entity\n\nQuestion: How many teats does a female goat sport ?\ntype: number\n\nQuestion: How is Answers.com different from KnowPost.com ?\ntype: description\n\nQuestion: Which area produces the least acidic coffee ?\ntype: location\n\nQuestion: What is the fear of frogs ?\ntype: entity\n\nQuestion: Where did the term `` 86'' come from ?\ntype: description\n\nQuestion: Who replaced Bert Parks as the host of The Miss America Pageant ?\ntype: human\n\nQuestion: Who reports the weather on the `` Good Morning America'' television show ?\ntype: human\n\nQuestion: What kind of animals were in the Paleozoic era ?\ntype: entity\n\nQuestion: How much will gas be taxed in California by the year 2000 ?\ntype: number\n\nQuestion: What number is at 12 o'clock on a dartboard ?\ntype: number\n\nQuestion: What was Mao, the Chinese leader's, full name ?\ntype: human\n\nQuestion: What is the richest state in the U.S. ?\ntype: location\n\nQuestion: How did the 7th inning stretch get started ?\ntype: description\n\nQuestion: What does Warner Bros. call a flightless cuckoo ?\ntype: entity\n\nQuestion: Who portrayed `` the man without a face'' in the movie of the same name ?\ntype: human\n\nQuestion: In the movie Groundshog Day what is the name of the character played by Andie MacDowell ?\ntype: human\n\nQuestion: A corgi is a kind of what ?\ntype: entity\n\nQuestion: Why do oceans contain salt water instead of fresh water ?\ntype: description\n\nQuestion: Who was in Death of a Salesman original movie, not 1985 ?\ntype: human\n\nQuestion: What is the movie Jonathan Livingstone Seagull ?\ntype: entity\n\nQuestion: What's the closest G2 Spectrum Yellow Dwarf to Earth ?\ntype: location\n\nQuestion: What does the River Seine empty into ?\ntype: location\n\nQuestion: What city is found in the city of OZ ?\ntype: location\n\nQuestion: Name a tiger that is extinct.\ntype: entity\n\nQuestion: How big is a baby bald eagle ?\ntype: number\n\nQuestion: How do you say 2 in Latin ?\ntype: entity\n\nQuestion: What desert has the highest sand dunes ?\ntype: location\n\nQuestion: What planet did Percival Lovell discover ?\ntype: location\n\nQuestion: How much money did the Marcos steal from their country ?\ntype: number\n\nQuestion: Whose cupboard was bare ?\ntype: human\n\nQuestion: What TV character sired a horse named Thunder ?\ntype: human\n\nQuestion: Where in a tree does photosynthesis occur ?\ntype: location\n\nQuestion: In order from the top, the four stripes on a can of Pepsi are what colors ?\ntype: entity\n\nQuestion: What is the origin of the word nevermind ?\ntype: description\n\nQuestion: Who was the king who signed the Magna Carta ?\ntype: human\n\nQuestion: What is the origin of the typing practice sentence `` Now is the time for all good men to come to the aid of their country'' ?\ntype: description\n\nQuestion: What is a biologist ?\ntype: description\n\nQuestion: How many counties are in Indiana ?\ntype: number\n\nQuestion: What TV show premiered on January 15, 1981 ?\ntype: entity\n\nQuestion: What is caffeine ?\ntype:"

inputs = tokenizer(sentence, return_tensors='pt')

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [16]:
model

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear(in_features=4096, out_features=1024, bias=False)
          (v_proj): Linear(in_features=4096, out_features=1024, bias=False)
          (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=4096, out_features=14336, bias=False)
          (up_proj): Linear(in_features=4096, out_features=14336, bias=False)
          (down_proj): Linear(in_features=14336, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((4096,), eps=1e-05)
      )
    )
    (n

In [17]:
model.eval()

output = model.generate(**inputs, max_new_tokens = 100, 
                            pad_token_id=tokenizer.eos_token_id, stop_strings = "\n\n", tokenizer=tokenizer, output_attentions = True, output_hidden_states = True, return_dict_in_generate = True)

In [23]:
output2 = model(**inputs, output_attentions = True, output_hidden_states = True, return_dict = True)

In [38]:
attn_by_layer = torch.vstack([output2.attentions[layer].detach()[:,:,-1,:] for layer in range(32)])

In [49]:
a = attn_by_layer.mean(dim=1)

In [57]:
inputs.input_ids.shape[1]

1785

In [18]:
output_str = tokenizer.decode(output.sequences.squeeze()[len(inputs.input_ids.squeeze()):])

In [19]:
output_str

' description\n\n'

In [20]:
output.attentions[1][0].shape

torch.Size([1, 32, 1, 1786])

In [37]:
tokenizer.decode([14924,    25,  3639,   374, 49750, 18072,  1337,    25])

'Question: What is caffeine?\ntype:'

In [48]:
layer=0
for l in output2.attentions[0]:
    attention_score_by_layer = l.squeeze()
    res = torch.zeros(attention_score_by_layer.shape[0],attention_score_by_layer.shape[2])
    i=0
    for h in attention_score_by_layer:
        attention_score_by_last_token = h[-1,:]
        res[i] = attention_score_by_last_token
        print(res[i])
        i+=1
    # res = res.mean(dim=0)
    # att_ratio_prompt = res[:-8].sum()
    # att_ratio_query = res[-8:].sum()
    # print(att_ratio_prompt, att_ratio_query, layer)
    # print("_______________________")
    layer+=1

tensor([1.1035e-03, 9.9065e-06, 1.2617e-06,  ..., 6.9398e-01, 1.1741e-02,
        1.6648e-02], grad_fn=<SelectBackward0>)
tensor([1.8874e-02, 1.4547e-04, 2.6731e-05,  ..., 1.3111e-01, 1.0900e-01,
        8.6950e-02], grad_fn=<SelectBackward0>)
tensor([1.9023e-02, 8.2296e-05, 4.9613e-05,  ..., 8.2547e-02, 4.1464e-01,
        3.9735e-01], grad_fn=<SelectBackward0>)
tensor([0.1365, 0.0002, 0.0004,  ..., 0.0275, 0.0033, 0.0361],
       grad_fn=<SelectBackward0>)
tensor([0.1004, 0.0002, 0.0005,  ..., 0.0289, 0.0067, 0.1189],
       grad_fn=<SelectBackward0>)
tensor([0.0514, 0.0007, 0.0006,  ..., 0.0269, 0.0028, 0.0903],
       grad_fn=<SelectBackward0>)
tensor([1.8360e-02, 1.1815e-04, 1.2054e-04,  ..., 1.7191e-02, 4.1829e-01,
        1.7495e-01], grad_fn=<SelectBackward0>)
tensor([2.0089e-03, 6.5488e-05, 3.8539e-05,  ..., 1.3961e-02, 6.8183e-01,
        7.0797e-02], grad_fn=<SelectBackward0>)
tensor([1.2349e-02, 3.3425e-04, 3.0888e-05,  ..., 9.1894e-03, 1.8073e-02,
        1.3431e-02], grad

In [30]:
res[:-12].sum()

tensor(0.7674)

In [40]:
from baukit import TraceDict


with TraceDict(model, layers = ['model.layers.12', 'model.layers.13'], retain_input=True, retain_output=True) as td:
    model(**inputs)

In [68]:
td['model.layers.12'].output

(tensor([[[-0.0262,  0.3578, -0.0736,  ...,  0.4321,  0.3053,  0.1958],
          [ 0.2324, -0.1933,  0.1212,  ..., -0.1416, -0.0911,  0.0119],
          [-0.1551,  0.0135, -0.0292,  ..., -0.1046,  0.0068,  0.1350],
          ...,
          [ 0.0872, -0.1376,  0.0152,  ...,  0.0065,  0.1807,  0.0288],
          [ 0.0626, -0.2305,  0.1866,  ..., -0.0289, -0.0213,  0.0405],
          [ 0.1151, -0.0209, -0.0755,  ...,  0.2087, -0.1086,  0.1950]]],
        grad_fn=<AddBackward0>),
 DynamicCache())

In [41]:
icv = td['model.layers.13'].input.detach()

In [43]:
icv.shape

torch.Size([1, 1785, 4096])

In [75]:
icv

tensor([ 0.1151, -0.0209, -0.0755,  ...,  0.2087, -0.1086,  0.1950])

In [93]:
def add_function_vector(edit_layer, fv_vector, device, idx=-1):
    """
    Adds a vector to the output of a specified layer in the model

    Parameters:
    edit_layer: the layer to perform the FV intervention
    fv_vector: the function vector to add as an intervention
    device: device of the model (cuda gpu or cpu)
    idx: the token index to add the function vector at

    Returns:
    add_act: a fuction specifying how to add a function vector to a layer's output hidden state
    """
    def add_act(output, layer_name):
        current_layer = int(layer_name.split(".")[2])
        if current_layer == edit_layer:
            if isinstance(output, tuple):
                output[0][:, idx] += fv_vector.to(device)
                return output
            else:
                return output
        else:
            return output

    return add_act

In [94]:
intervention_fn = add_function_vector(13, icv.reshape(1, 4096), model.device, idx=-1)

prompt2 = "Classify the type of answer from given question.\nQuestion: How long is Camptown Racetrack ?\ntype: number\n\nQuestion: What is the name of the brilliant British economist behind its creation ?\ntype: human\n\nQuestion: Where do I find information for foreclosure properties on the Internet ?\ntype: location\n\nQuestion: Where did Ty Cobb grow up ?\ntype: location\n\nQuestion: How many teaspoons make up a tablespoon ?\ntype: number\n\nQuestion: What baseball expression came from the nautical term for ships sailing between the Atlantic and Pacific before the Panama Canal ?\ntype: description\n\nQuestion: What animal has been called The Poor Man's Cow ?\ntype: entity\n\nQuestion: What book opens : `` At a certain village in La Mancha, which I shall not name...'' ?\ntype: entity\n\nQuestion: What is the origin of the word, magic ?\ntype: description\n\nQuestion: Name the blind sculptress in love with the Fantastic Four's Thing.\ntype: human\n\nQuestion: Where can I find info on Alexander Mackenzie ?\ntype: location\n\nQuestion: How many years ago did Led Zeppelin release its last album ?\ntype: number\n\nQuestion: What does God create in the first sentence of the Bible ?\ntype: entity\n\nQuestion: What is the price for tuberculosis drugs ?\ntype: number\n\nQuestion: What were Baffin, Frobisher and Franklin looking for ?\ntype: entity\n\nQuestion: What do the red-and-white stripes on a barbershop pole stand for ?\ntype: description\n\nQuestion: How do doctors diagnose bone cancer ?\ntype: description\n\nQuestion: Where can I find a world atlas map online at no charge ?\ntype: location\n\nQuestion: In which Tennessee Williams play is one of the characters killed and devoured by a mob of starving children ?\ntype: entity\n\nQuestion: In what year did they build the Berlin Wall ?\ntype: number\n\nQuestion: What are the Nordic nations ?\ntype: location\n\nQuestion: Name the vessel used by the Atari Force in the DC comics.\ntype: entity\n\nQuestion: What are values ?\ntype: description\n\nQuestion: Where is McCarren Airport ?\ntype: location\n\nQuestion: Which of the following people is not associated with Andy Warhol ?\ntype: human\n\nQuestion: What information can you get me on Fairground Park in St. Louis\ntype: description\n\nQuestion: What according to the Kinsey Institute, is the sexual preference of four percent of American males ?\ntype: description\n\nQuestion: What is the origin of the term `` buffalo wings'' that is used as a menu item in bars across the nation for chicken wings in a spicey sauce ?\ntype: description\n\nQuestion: Who was the original Humpty Dumpty ?\ntype: human\n\nQuestion: How many equal sides are there on a scalene triangle ?\ntype: number\n\nQuestion: Where is Windsor Castle ?\ntype: location\n\nQuestion: Who directed The Wild Bunch ?\ntype: human\n\nQuestion: What is the chromosome number of an elephant ?\ntype: number\n\nQuestion: Where is Qatar ?\ntype: location\n\nQuestion: Who invented the Wonderbra ?\ntype: human\n\nQuestion: What is an example of an actual case of using the Fourteenth Amendment ?\ntype: description\n\nQuestion: What kind of creatures are the Canary Islands named for ?\ntype: entity\n\nQuestion: How can I register my website in Yahoo for free ?\ntype: description\n\nQuestion: What is the seafaring name for the southern tip of South America ?\ntype: location\n\nQuestion: Where can I find a case on Americans with Disabilities Act of 199 ?\ntype: location\n\nQuestion: What are those little blue reflectors in the middle of the road for ?\ntype: description\n\nQuestion: What California bridge was Don Brown the first to cross, on May 27, 1937 ?\ntype: location\n\nQuestion: What card game derived its name from biritch, or Russian Whist ?\ntype: entity\n\nQuestion: What company's logo is a `` W'' in a circle ?\ntype: human\n\nQuestion: What is a portal ?\ntype: description\n\nQuestion: What disease did August von Wassermann develop a specific test for in 196 ?\ntype: entity\n\nQuestion: What's the abbreviation for trinitrotoluene ?\ntype: abbreviation\n\nQuestion: Where did Bill Gates go to college ?\ntype: location\n\nQuestion: On what T.V. show could Tom Terrific be found ?\ntype: entity\n\nQuestion: Why do some clothing labels say `` Use a nonchlorine bleach'' ?\ntype: description\n\nQuestion: What is IOC an abbreviation of ?\ntype: abbreviation\n\nQuestion: What Nazi leader killed himself in jail just before he was to be executed as a war criminal ?\ntype: human\n\nQuestion: Who is the head of the World Bank ?\ntype: human\n\nQuestion: Who is the Prophet of Medina ?\ntype: human\n\nQuestion: Who discovered imaginary numbers ?\ntype: human\n\nQuestion: Which of the following famous people does not paint as a hobby ?\ntype: human\n\nQuestion: What is a caul ?\ntype: description\n\nQuestion: What does saliva consist of ?\ntype: entity\n\nQuestion: What capital is built around Monument Circle which contains soldiers and sailors monument ?\ntype: location\n\nQuestion: What are some tips for building a fire in a fireplace ?\ntype: entity\n\nQuestion: What deck of cards includes the Wheel of Fortune, the Lovers, and Death ?\ntype: entity\n\nQuestion: How many teats does a female goat sport ?\ntype: number\n\nQuestion: How is Answers.com different from KnowPost.com ?\ntype: description\n\nQuestion: Which area produces the least acidic coffee ?\ntype: location\n\nQuestion: What is the fear of frogs ?\ntype: entity\n\nQuestion: Where did the term `` 86'' come from ?\ntype: description\n\nQuestion: Who replaced Bert Parks as the host of The Miss America Pageant ?\ntype: human\n\nQuestion: Who reports the weather on the `` Good Morning America'' television show ?\ntype: human\n\nQuestion: What kind of animals were in the Paleozoic era ?\ntype: entity\n\nQuestion: How much will gas be taxed in California by the year 2000 ?\ntype: number\n\nQuestion: What number is at 12 o'clock on a dartboard ?\ntype: number\n\nQuestion: What was Mao, the Chinese leader's, full name ?\ntype: human\n\nQuestion: What is the richest state in the U.S. ?\ntype: location\n\nQuestion: How did the 7th inning stretch get started ?\ntype: description\n\nQuestion: What does Warner Bros. call a flightless cuckoo ?\ntype: entity\n\nQuestion: Who portrayed `` the man without a face'' in the movie of the same name ?\ntype: human\n\nQuestion: In the movie Groundshog Day what is the name of the character played by Andie MacDowell ?\ntype: human\n\nQuestion: A corgi is a kind of what ?\ntype: entity\n\nQuestion: Why do oceans contain salt water instead of fresh water ?\ntype: description\n\nQuestion: Who was in Death of a Salesman original movie, not 1985 ?\ntype: human\n\nQuestion: What is the movie Jonathan Livingstone Seagull ?\ntype: entity\n\nQuestion: What's the closest G2 Spectrum Yellow Dwarf to Earth ?\ntype: location\n\nQuestion: What does the River Seine empty into ?\ntype: location\n\nQuestion: What city is found in the city of OZ ?\ntype: location\n\nQuestion: Name a tiger that is extinct.\ntype: entity\n\nQuestion: How big is a baby bald eagle ?\ntype: number\n\nQuestion: How do you say 2 in Latin ?\ntype: entity\n\nQuestion: What desert has the highest sand dunes ?\ntype: location\n\nQuestion: What planet did Percival Lovell discover ?\ntype: location\n\nQuestion: How much money did the Marcos steal from their country ?\ntype: number\n\nQuestion: Whose cupboard was bare ?\ntype: human\n\nQuestion: What TV character sired a horse named Thunder ?\ntype: human\n\nQuestion: Where in a tree does photosynthesis occur ?\ntype: location\n\nQuestion: In order from the top, the four stripes on a can of Pepsi are what colors ?\ntype: entity\n\nQuestion: What is the origin of the word nevermind ?\ntype: description\n\nQuestion: Who was the king who signed the Magna Carta ?\ntype: human\n\nQuestion: What is the origin of the typing practice sentence `` Now is the time for all good men to come to the aid of their country'' ?\ntype: description\n\nQuestion: What is a biologist ?\ntype: description\n\nQuestion: How many counties are in Indiana ?\ntype: number\n\nQuestion: What TV show premiered on January 15, 1981 ?\ntype: entity\n\nQuestion: What is caffeine ?\ntype:"
inputs2 = tokenizer(prompt2, return_tensors='pt')
with TraceDict(model, layers = ['model.layers.13'], edit_output=intervention_fn):
    output = model.generate(inputs2.input_ids, max_new_tokens = 100, 
                            pad_token_id=tokenizer.eos_token_id, stop_strings = "\n\n", tokenizer=tokenizer)
    intervention_output = tokenizer.decode(output.squeeze()[len(inputs2.input_ids.squeeze()):])

In [95]:
intervention_output

' description\n\n'

In [97]:
from sklearn.metrics import f1_score

gt = ["A", "B", "C", "E", "A", "D"]
pred = ["B", "a", "C", "D", "D", "D"]

f1 = f1_score(gt, pred, average='macro')

In [98]:
f1

0.25

In [3]:
import torch
x = torch.tensor([[3.0, 4.0]])
l2_norm = torch.norm(x)
print("L2 Norm:", l2_norm)

L2 Norm: tensor(5.)


In [56]:
x = [1,2,3,4,5,6,7]
x[-3:]

[5, 6, 7]